services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: chatbot_app_prod
    environment:
      APP_ENV: production
    env_file: .env
    # FORZAMOS EL DIRECTORIO DE TRABAJO
    working_dir: /var/www/html

    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: chatbot_nginx_prod
    ports:
      - "${APP_PORT:-8002}:80"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    depends_on:
      - app
    restart: always
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: chatbot_mysql_prod
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: [ "mysqld", "--mysqlx=0" ]
    volumes:
      - chatbot_dbdata_prod:/var/lib/mysql
    restart: always
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: chatbot_redis_prod
    restart: always
    networks:
      - backend

  queue:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: chatbot_queue_prod
    command: php artisan horizon
    env_file: .env
    # FORZAMOS EL DIRECTORIO DE TRABAJO TAMBIÉN AQUÍ
    working_dir: /var/www/html

    depends_on: [ app, redis ]
    restart: always
    networks: [ backend ]

  telegram_poll:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.prod
    container_name: chatbot_tg_poll_prod
    command: php artisan telegram:poll-all
    env_file: .env
    working_dir: /var/www/html
    depends_on:
      - app
      - mysql
      - redis
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  chatbot_dbdata_prod:
    driver: local
